/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2_etapa1_arthurguardieiro_carlosmoraes_rodrigomartins;

import java.awt.Color;
import java.awt.event.*;
import java.util.ArrayList;

import javax.swing.*;

/**
 *
 * @author Carlos
 */
public class Loja extends JFrame {
    
    public static Color corFundoEscura = Color.darkGray;
    public static Color corFundoClara = Color.lightGray;
    public static Color corFonteClara = Color.white;
    public static Color corFonteEscura = Color.black;
    public static Color corDestaque = Color.white;

    private static ArrayList<Cliente> clientes = new ArrayList<>();
    private static ArrayList<Pedido> pedidos = new ArrayList<>();

    /**
     * Creates new form Loja
     *
     */
    public Loja() {
        initComponents();
        setBounds(0, 0, 1280, 720);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println(e);
            }
        });
    }

    public static Pedido buscaPedido(int codigo) {
        for (Pedido pd : pedidos) {
            if (pd.getCodigo() == codigo) {
                return pd;
            }
        }
        return null;
    }

    public static boolean confirmaCadastro(String cpf) {
        for (Cliente cl : clientes) {
            if (cl.getCpf().equalsIgnoreCase(cpf)) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameProcurar = new javax.swing.JFrame();
        labelProcurar = new javax.swing.JLabel();
        fieldProcurar = new javax.swing.JTextField();
        buttonProcurar = new javax.swing.JButton();
        frameExcluirCliente = new javax.swing.JFrame();
        labelExcluir = new javax.swing.JLabel();
        fieldExcluir = new javax.swing.JTextField();
        buttonExcluir = new javax.swing.JButton();
        painelCliente = new javax.swing.JPanel();
        buttonNovoCliente = new javax.swing.JButton();
        buttonProcurarCliente = new javax.swing.JButton();
        buttonExcluirCliente = new javax.swing.JButton();
        painelPedido = new javax.swing.JPanel();
        menuPedidos = new javax.swing.JPanel();
        buttonNovoPedido = new javax.swing.JButton();
        buttonProcurarPedido = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        Arquivo = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();

        frameProcurar.setSize(new java.awt.Dimension(400, 250));
        frameProcurar.getContentPane().setLayout(new java.awt.GridLayout());

        labelProcurar.setText("jLabel1");
        frameProcurar.getContentPane().add(labelProcurar);

        fieldProcurar.setText("jTextField1");
        frameProcurar.getContentPane().add(fieldProcurar);

        buttonProcurar.setText("OK");
        frameProcurar.getContentPane().add(buttonProcurar);

        frameExcluirCliente.setSize(new java.awt.Dimension(400, 250));
        frameExcluirCliente.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        labelExcluir.setText("jLabel1");
        frameExcluirCliente.getContentPane().add(labelExcluir);

        fieldExcluir.setText("jTextField1");
        frameExcluirCliente.getContentPane().add(fieldExcluir);

        buttonExcluir.setText("OK");
        frameExcluirCliente.getContentPane().add(buttonExcluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja");
        setBackground(Loja.corFundoEscura);
        setName("frameLoja"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        painelCliente.setBackground(Loja.corFundoEscura);
        painelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(Loja.corFundoClara, Loja.corFundoEscura), "Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), Loja.corDestaque)); // NOI18N
        painelCliente.setPreferredSize(new java.awt.Dimension(200, 200));
        painelCliente.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        buttonNovoCliente.setBackground(Loja.corFundoClara);
        buttonNovoCliente.setForeground(Loja.corFonteEscura);
        buttonNovoCliente.setText("Novo Cliente");
        buttonNovoCliente.setAlignmentX(0.5F);
        buttonNovoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonNovoCliente.setMargin(new java.awt.Insets(2, 20, 2, 20));
        buttonNovoCliente.setMaximumSize(new java.awt.Dimension(200, 200));
        buttonNovoCliente.setName("Novo Cliente"); // NOI18N
        buttonNovoCliente.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoClienteActionPerformed(evt);
            }
        });
        painelCliente.add(buttonNovoCliente);

        buttonProcurarCliente.setBackground(Loja.corFundoClara);
        buttonProcurarCliente.setForeground(Loja.corFonteEscura);
        buttonProcurarCliente.setText("Procurar Cliente");
        buttonProcurarCliente.setAlignmentX(0.5F);
        buttonProcurarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonProcurarCliente.setMargin(new java.awt.Insets(2, 20, 2, 20));
        buttonProcurarCliente.setMaximumSize(new java.awt.Dimension(200, 200));
        buttonProcurarCliente.setName("Novo Cliente"); // NOI18N
        buttonProcurarCliente.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonProcurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcurarClienteActionPerformed(evt);
            }
        });
        painelCliente.add(buttonProcurarCliente);

        buttonExcluirCliente.setBackground(Loja.corFundoClara);
        buttonExcluirCliente.setForeground(Loja.corFonteEscura);
        buttonExcluirCliente.setText("Excluir Cliente");
        buttonExcluirCliente.setAlignmentX(0.5F);
        buttonExcluirCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonExcluirCliente.setMargin(new java.awt.Insets(2, 20, 2, 20));
        buttonExcluirCliente.setMaximumSize(new java.awt.Dimension(200, 200));
        buttonExcluirCliente.setName("Novo Cliente"); // NOI18N
        buttonExcluirCliente.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirClienteActionPerformed(evt);
            }
        });
        painelCliente.add(buttonExcluirCliente);

        getContentPane().add(painelCliente);

        painelPedido.setBackground(Loja.corFundoEscura);
        painelPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(Loja.corDestaque, Loja.corFundoClara), "Pedidos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), Loja.corFonteClara)); // NOI18N
        painelPedido.setPreferredSize(new java.awt.Dimension(450, 200));
        painelPedido.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        menuPedidos.setBackground(new java.awt.Color(153, 153, 153));
        menuPedidos.setOpaque(false);

        buttonNovoPedido.setBackground(Loja.corFundoClara);
        buttonNovoPedido.setForeground(Loja.corFonteEscura);
        buttonNovoPedido.setText("Novo Pedido");
        buttonNovoPedido.setAlignmentX(0.5F);
        buttonNovoPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonNovoPedido.setMargin(new java.awt.Insets(2, 20, 2, 20));
        buttonNovoPedido.setMaximumSize(new java.awt.Dimension(200, 200));
        buttonNovoPedido.setName("Novo Cliente"); // NOI18N
        buttonNovoPedido.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoPedidoActionPerformed(evt);
            }
        });
        menuPedidos.add(buttonNovoPedido);

        buttonProcurarPedido.setBackground(Loja.corFundoClara);
        buttonProcurarPedido.setForeground(Loja.corFonteEscura);
        buttonProcurarPedido.setText("Procurar Pedido");
        buttonProcurarPedido.setAlignmentX(0.5F);
        buttonProcurarPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonProcurarPedido.setMargin(new java.awt.Insets(2, 20, 2, 20));
        buttonProcurarPedido.setMaximumSize(new java.awt.Dimension(200, 200));
        buttonProcurarPedido.setName("Novo Cliente"); // NOI18N
        buttonProcurarPedido.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonProcurarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcurarPedidoActionPerformed(evt);
            }
        });
        menuPedidos.add(buttonProcurarPedido);

        painelPedido.add(menuPedidos);

        getContentPane().add(painelPedido);

        menuPrincipal.setBackground(Loja.corFundoEscura);
        menuPrincipal.setForeground(Loja.corFonteClara);

        Arquivo.setForeground(new java.awt.Color(255, 255, 255));
        Arquivo.setText("Arquivo");

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Arquivo.add(Sair);

        menuPrincipal.add(Arquivo);

        setJMenuBar(menuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoClienteActionPerformed
        Cliente novoCadastro = new Cliente();
        novoCadastro.iniciarCadastro(clientes);
    }//GEN-LAST:event_buttonNovoClienteActionPerformed

    private void buttonNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoPedidoActionPerformed
        Pedido novo = new Pedido();
        menuPedidos.setVisible(false);
        novo.setVisible(true);
        painelPedido.add(novo);
        novo.iniciarCadastro(() -> {   
            novo.setVisible(false);
            painelPedido.remove(novo);
            menuPedidos.setVisible(true);
            pedidos.add(novo);            
        });        
    }//GEN-LAST:event_buttonNovoPedidoActionPerformed

    private void buttonProcurarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcurarPedidoActionPerformed
        frameProcurar.setVisible(true);
        frameProcurar.setTitle("Procurar Pedido: ");
        labelProcurar.setText("Codigo do pedido: ");
        fieldProcurar.setText("");
        buttonProcurar.addActionListener((e) -> {
            Pedido encontrado = null;
            for (Pedido pd : pedidos) {
                encontrado = buscaPedido(Integer.parseInt(fieldProcurar.getText()));
                if (encontrado != null) {
                    encontrado.mostrarInfo();
                } else {
                    JOptionPane.showMessageDialog(null, "Pedido não encontrado.");
                }
            }
        });
    }//GEN-LAST:event_buttonProcurarPedidoActionPerformed

    private void buttonProcurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcurarClienteActionPerformed
        frameProcurar.setVisible(true);
        frameProcurar.setTitle("Procurar Cliente: ");
        labelProcurar.setText("cpf do cliente: ");
        fieldProcurar.setText("");
        buttonProcurar.addActionListener((e) -> {
            for (Cliente cl : clientes) {
                if (cl.getCpf().equalsIgnoreCase(fieldProcurar.getText())) {
                    cl.mostrarInfo();
                } else {
                    JOptionPane.showMessageDialog(null, "Cliente não encontrado.");
                }
            }
        });
    }//GEN-LAST:event_buttonProcurarClienteActionPerformed

    private void buttonExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirClienteActionPerformed
        frameExcluirCliente.setVisible(true);
        frameExcluirCliente.setTitle("Excluir cliente");
        labelExcluir.setText("Digite o cpf: ");
        fieldExcluir.setText("");
        buttonExcluir.addActionListener((e) -> {
            if(!Loja.confirmaCadastro(fieldExcluir.getText())){
                int indice=0;
                for(Cliente cl: clientes){
                    if(cl.getCpf().equals(fieldExcluir.getText())){
                        indice = clientes.indexOf(cl);
                    }
                }
                System.out.println("Excluido "+ clientes.get(indice));
                clientes.remove(indice);
                JOptionPane.showMessageDialog(null, "Cliente excluido.");
            } else{
                JOptionPane.showMessageDialog(null, "CPF não encontrado.");
                System.out.println("cpf nao encontrado");
            }
        });
    }//GEN-LAST:event_buttonExcluirClienteActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Arquivo;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonExcluirCliente;
    private javax.swing.JButton buttonNovoCliente;
    private javax.swing.JButton buttonNovoPedido;
    private javax.swing.JButton buttonProcurar;
    private javax.swing.JButton buttonProcurarCliente;
    private javax.swing.JButton buttonProcurarPedido;
    private javax.swing.JTextField fieldExcluir;
    private javax.swing.JTextField fieldProcurar;
    private javax.swing.JFrame frameExcluirCliente;
    private javax.swing.JFrame frameProcurar;
    private javax.swing.JLabel labelExcluir;
    private javax.swing.JLabel labelProcurar;
    private javax.swing.JPanel menuPedidos;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel painelCliente;
    private javax.swing.JPanel painelPedido;
    // End of variables declaration//GEN-END:variables
}
